name = "Lightsail Server"
author = "OrzMiku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fba55cf52a3e0a49b0baac552a366b579fa433eea1ef3c24919ae35dbb7ea75"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
