name = "Lightsail Server"
author = "OrzMiku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c71e44299d516711f1681b48bf1dd74759a743c22a5efa2a895e970d2f96c6b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
