name = "Lightsail Server"
author = "OrzMiku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57451cee4c9b4c16be1cfe22c45bf4053932812aadde13453a77a5da7a00bd6c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
